#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    arr = []
    totals = []

for z in range(6):

   arr_t = [int(arr_temp) for arr_temp in input().strip().split(' ')]
   arr.append(arr_t)

for x, i in enumerate(arr):

    for y, j in enumerate(i):

        if (y < len(i) - 2) and (x < len(arr) - 2):

            n = arr[x][y] + arr[x][y+1] + arr[x][y+2] + \
                arr[x+1][y+1] + \
                arr[x+2][y] + arr[x+2][y+1] + arr[x+2][y+2]

            totals.append(n)

print(max(totals))
