#!/bin/python3

def inputs():
    global S
    S = input() 
    if (len(S) in range (2, 10001)):
        s1 = S[0::2]
        s2 = S[1::2]
        print (s1 + " " +s2)    

T = int(input())
if (1<=T<=10):
    for i in range (0,T):
        inputs()
