#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input())
 
if (1<=n<=1001):
    arr = list(map(int, input().rstrip().split()))
    print(*arr[::-1])
